### ISSUE TITLE
host:port error

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#758]
1. User enters connection information in SlamData.
2. Cannot connect.
3. User restarts.
4. Error message below prints out.

There may be a problem on the front-end, too -- in fact, I suspect there is -- please report that as well if it turns out to be the case.

Probably the API allows storage of incorrect / invalid URI data, which explodes the server on restart. The API should not allow adding mounts unless they are valid.

I will work with the user to get the structure of the Connection URI.

```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.simontuffs.onejar.Boot.run(Boot.java:340)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
at com.install4j.runtime.launcher.MacLauncher.main(Unknown Source)
Caused by: com.mongodb.MongoException: host and port should be specified in host:port format
at com.mongodb.ServerAddress.<init>(ServerAddress.java:122)
at com.mongodb.ServerAddress.<init>(ServerAddress.java:49)
at com.mongodb.Mongo.createCluster(Mongo.java:618)
at com.mongodb.Mongo.<init>(Mongo.java:283)
at com.mongodb.MongoClient.<init>(MongoClient.java:265)
at slamdata.engine.physical.mongodb.util$$anonfun$1.apply(util.scala:13)
at slamdata.engine.physical.mongodb.util$$anonfun$1.apply(util.scala:12)
at scalaz.MemoFunctions$$anonfun$mutableMapMemo$1$$anonfun$apply$2$$anonfun$apply$3.apply(Memo.scala:67)
at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
at scalaz.MemoFunctions$$anonfun$mutableMapMemo$1$$anonfun$apply$2.apply(Memo.scala:67)
at slamdata.engine.physical.mongodb.util$$anonfun$2$$anonfun$apply$1.apply(util.scala:16)
at slamdata.engine.physical.mongodb.util$$anonfun$2$$anonfun$apply$1.apply(util.scala:16)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$.Try(Task.scala:379)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Future.step(Future.scala:111)
at scalaz.concurrent.Future.listen(Future.scala:76)
at scalaz.concurrent.Future.runAsync(Future.scala:143)
at scalaz.concurrent.Future.run(Future.scala:160)
at scalaz.concurrent.Task.run(Task.scala:97)
at slamdata.engine.api.Server$.main(server.scala:120)
at slamdata.engine.api.Server.main(server.scala)
... 12 more
```

**Comment by garyb** [comment]
I'm interested to see what that URI is also. The front end should disallow invalid URIs - it won't let you enter non numeric values in the field, and is now using `purescript-uri` to parse and pretty print the connection URI - it definitely won't parse non-numeric ports.

**Comment by mossprescott** [comment]
I saw this problem when the demo's configuration got broken. There was an
extra slash after the port.

**Comment by jdegoes** [comment]
@garyb Can you see if the front-end might produce an extra slash after the port (e.g. `foo.com:1223//...`)?

**Comment by garyb** [comment]
Ack, sorry, yes it can do if you enter `/` as the path. I'll whip up a fix.
