### ISSUE TITLE
API should error when attempting to nest mongodb mounts

### ISSUE THREAD

**Issue by garyb** [slamdata/slamengine#788]
See discussion with @jdegoes on slamdata/slamdata#298. This might just fall under the "proper" fix for #781, but thought it was worth raising explicitly too.

**Comment by jdegoes** [comment]
@sellout This can probably be bundled with your other mount fixes as it will be the same area of the code.

**Comment by sellout** [comment]
Yep.

**Comment by garyb** [comment]
I think this might need looking at again - making an illegal change like this in the API doesn't raise an error, instead an exception is thrown when the server restarts:
```
Exception in thread "Thread-10" attempting to mount a backend within an existing backend.
slamdata.engine.Mounter$.slamdata$engine$Mounter$$rec$1(mounter.scala:29)
slamdata.engine.Mounter$.slamdata$engine$Mounter$$rec$1(mounter.scala:27)
slamdata.engine.Mounter$$anonfun$mountE$1$$anonfun$apply$1.apply(mounter.scala:35)
slamdata.engine.Mounter$$anonfun$mountE$1$$anonfun$apply$1.apply(mounter.scala:35)
  ... (17)
slamdata.engine.api.Server$$anonfun$slamdata$engine$api$Server$$runAsync$1$1$$anon$2.run(server.scala:43)
	at slamdata.engine.Mounter$.slamdata$engine$Mounter$$rec$1(mounter.scala:29)
	at slamdata.engine.Mounter$.slamdata$engine$Mounter$$rec$1(mounter.scala:27)
	at slamdata.engine.Mounter$$anonfun$mountE$1$$anonfun$apply$1.apply(mounter.scala:35)
	at slamdata.engine.Mounter$$anonfun$mountE$1$$anonfun$apply$1.apply(mounter.scala:35)
	at scalaz.EitherT$$anonfun$flatMap$1$$anonfun$apply$4.apply(EitherT.scala:91)
	at scalaz.$bslash$div.fold(Either.scala:57)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:91)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:91)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$.Try(Task.scala:379)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
	at scalaz.concurrent.Future.step(Future.scala:110)
	at scalaz.concurrent.Future.listen(Future.scala:76)
	at scalaz.concurrent.Future.runAsync(Future.scala:143)
	at scalaz.concurrent.Future.run(Future.scala:160)
	at scalaz.concurrent.Task.run(Task.scala:97)
	at slamdata.engine.api.Server$$anonfun$slamdata$engine$api$Server$$runAsync$1$1$$anon$2.run(server.scala:43)
```

**Comment by sellout** [comment]
Argh, I only handled this in POST, not PUT.

**Comment by sellout** [comment]
So, semantics for this on PUT … if a mount exists at /foo and you try to PUT one at /foo/bar, then that seems like clearly a 409 (Conflict). But, if a mount exists at /foo/bar, and you try to PUT one at /foo, that’s less obvious to me. Could be a 409, but could also replace the directory at /foo (and get rid of all mounts below it) with the new mount. That behavior may also be non-obvious, though.

**Comment by mossprescott** [comment]
I don't see why that's any less conflicting. The point is you can't add the new one without deleting something that already exists, so it's a conflict. The client can resolve it by doing the delete itself.

**Comment by sellout** [comment]
It’s less conflicting because PUT is intended to replace something that’s already there. In this case, it would replace the filesystem at /foo/ (which has children filesystems) with the new filesystem.

But yeah, I’m on board with PUT not succeeding unless it is a new path or exactly replacing one mount.

**Comment by mossprescott** [comment]
Went looking for in the spec for something that says PUT should not have the effect of deleting something else, but of course the spec isn't prescriptive on that level.

What it does say is "a PUT request on a general URI might result in several other URIs being defined by the origin server." [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) To me, the implication is that PUT is for adding stuff, and should not have other effects. Of course, the very next line says "HTTP/1.1 does not define how a PUT method affects the state of an origin server," so there you go.

**Comment by jdegoes** [comment]
> Could be a 409, but could also replace the directory at /foo (and get rid of all mounts below it) with the new mount. That behavior may also be non-obvious, though.

The later behavior is the one I would prefer, If a PUT would succeed without anything there, then I believe it must succeed with something there, by property of being idempotent (one can argue the hierarchical nature of a file system should result in slightly different semantics, of course).

It's up to the front-end to give good feedback and ensure users know exactly what's going on at all times.

**Comment by sellout** [comment]
Ok, a point against the deleting the trees … this is the /mount API. Currently (given a mount at /foo/bar/), if we GET /foo/, we 404. if we DELETE /foo/, we 200 with a NOP. So now I’m leaning toward PUT /foo/ being 409, since we can’t replace the nothing at /foo/.

**Comment by jdegoes** [comment]
OK, I buy that. :+1: Needs to be documented on the README.

**Comment by sellout** [comment]
Definitely worth thinking about whether GET /foo/ should be 403 (Forbidden … or maybe something else), DELETE could do the same, or cascade across the children, _then_ PUT could drop any child mounts when adding a new one.
