### ISSUE TITLE
failure to start slamengine in sd 2.0

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#797]
```
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.simontuffs.onejar.Boot.run(Boot.java:340)
at com.simontuffs.onejar.Boot.main(Boot.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
at com.exe4j.runtime.WinLauncher.main(Unknown Source)
at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)
Caused by: java.io.IOException: Failed to open http://localhost:2000/. Error message: A device attached to the system is not functioning.

at sun.awt.windows.WDesktopPeer.ShellExecute(Unknown Source)
at sun.awt.windows.WDesktopPeer.browse(Unknown Source)
at java.awt.Desktop.browse(Unknown Source)
at slamdata.engine.api.Server$$anonfun$openBrowser$1.apply$mcV$sp(server.scala:89)
at slamdata.engine.api.Server$$anonfun$openBrowser$1.apply(server.scala:89)
at slamdata.engine.api.Server$$anonfun$openBrowser$1.apply(server.scala:89)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
at scalaz.concurrent.Task$.Try(Task.scala:379)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
at scalaz.concurrent.Future.step(Future.scala:111)
at scalaz.concurrent.Future.listen(Future.scala:76)
at scalaz.concurrent.Future.runAsync(Future.scala:143)
at scalaz.concurrent.Future.run(Future.scala:160)
at scalaz.concurrent.Task.run(Task.scala:97)
at slamdata.engine.api.Server$.main(server.scala:107)
at slamdata.engine.api.Server.main(server.scala)
... 13 more
```

**Comment by jdegoes** [comment]
First reported in slamdata/slamdata#310 by @sivaramsi.

**Comment by sivaramsi** [comment]
when will this be ready .

**Comment by jdegoes** [comment]
@sivaramsi I am not sure, but we will try to take a look as soon as we can. I suspect some difficulty with either the port (2000), the network interface card on your computer, or possibly your Windows security settings / software. I recommend, as a workaround, to try installing the software on another machine (e.g. your home machine), as it will likely work just fine there. 

Possibly, you could accelerate this ticket by providing more information on your system (whether port 2000 is already taken, information on your NIC, information on your security settings, version of Windows you are running, etc.).

**Comment by sivaramsi** [comment]
I tried with different ports but the result is same ... since you have used 8080 in the demo i have used that port too but no improvement, i got the same exception

**Comment by sellout** [comment]
Hi @sivaramsi,

What version of SlamData are you using? One you downloaded from the site, or did you clone the git repo? I just want to make sure I try to replicate this with the same versions.

Also, this is happening after the server is running, when we try to open a browser window to the service. Failing to open a browser window shouldn’t cause the server to crash, so I’ll handle this error to keep the server running, and then, worst case, you have to manually navigate to the URL.

**Comment by sellout** [comment]
As near as I can tell, this error is due to something on your system. Unfortunately, the causes seem pretty varied – from a problem with a connected device (which makes sense given the message, but not for SlamData) to corrupted system files.

Hopefully the commit referenced above (#798) will help you when we build our next release, but I’m not sure what we can do to resolve the underlying issue.

**Comment by jdegoes** [comment]
@sivaramsi 2.0.10 will be out tomorrow and should at least allow you to open your web browser manually to the right location. If you encounter difficulty, please open a new ticket. I will close this one for now since the problem seems to be on your system.

**Comment by sivaramsi** [comment]
ok , will try 2.0.10 ..
